config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mypage.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('write/', views.post_write, name='write'),
    path('about/', views.about, name="about"),
    # views.post_detail를 통해 가져온 post_id 정보를 바탕으로 url 구성
    # posts/1 -> post_id = 1 인 상세페이지로 이동
    path('posts/<int:post_id>/', views.post_detail, name="posts"),
    # 위와 동일
    path('category/', views.category, name='category'),
    path('category/<str:cate_name>/', views.select_category, name='category'),
    path('option/', views.category_option, name='category option'),
    path('option/delete/<int:category_id>', views.category_delete, name='category delete'),
    path('option/modify/<int:category_id>', views.category_modify, name='category modify'),
    path('modify/<int:post_id>/', views.modify, name="modify"),
    path('delete/<int:post_id>/', views.delete, name="delete"),
    path('comment/<int:comments_id>/', views.delete_comment, name="delete_comment"),
]

mypage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

class User(AbstractUser):
    pass

class Category(models.Model):
    cate_name = models.CharField(max_length=50)

    def __str__(self):
        return self.cate_name

class Post(models.Model):
    cate = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    p_title = models.CharField(max_length=50)
    p_desc = models.CharField(max_length=100)
    p_contents = MarkdownxField()
    p_created = models.DateTimeField(auto_now_add=True, null=True)
    p_updated = models.DateTimeField(auto_now=True, null=True)
    thumbnail = models.ImageField(upload_to="post", blank=True)

    def __str__(self):
        return self.p_title
    
    def get_content_markdown(self):
        return markdown(self.p_contents)

class Comments(models.Model):
    p = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    c_user_id = models.CharField(max_length=20)
    c_user_pw = models.CharField(max_length=20)
    c_contents = models.TextField()
    c_created = models.DateTimeField(auto_now_add=True)
    c_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.c_contents

mypage/views.py
from django.shortcuts import render, redirect

# https://velog.io/@may_soouu/%EC%9E%A5%EA%B3%A0-Annotate-Aggregate 
from django.db.models import Count, F
from django.db.models.functions import Lower

from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from .models import Category
from .models import Post
from .models import Comments

# index.html / 메인페이지
def main(request):
    # categorys에 post_count 변수명으로 post의 개수 정보 추가
    categorys = Category.objects.annotate(post_count=Count('post')).order_by('cate_name')
    # posts에 comments_count 변수명으로 comment의 개수 정보 추가 + 역순으로 출력시켜 최신순으로 보이도록 함
    # category_title에 외래키 정보인 category 테이블의 cate_name 정보를 category_title에 입력시켜 줌
    posts = Post.objects.annotate(comments_count=Count('comments'), category_title=F('cate__cate_name')).order_by('-id')
    
    # 전체 포스트의 개수를 세기 위한 all_post 변수
    all_post = 0
    for category in categorys:
        all_post += category.post_count
    
    context = {'categorys': categorys, 'posts' : posts, 'all_post' : all_post}
    return render(request, 'mypage/index.html', context)

def category(request):

    categorys = Category.objects.annotate(post_count=Count('post'), lower_name=Lower('cate_name')).order_by('cate_name')
    context = {'categorys': categorys}
    return render(request, 'mypage/category.html', context)

# category.html / 카테고리 선택 페이지
def select_category(request, cate_name):
    # lower_name 변수에 Category 테이블의 cate_name 데이터를 모두 소문자화시켜 넣어줌
    categorys = Category.objects.annotate(post_count=Count('post'), lower_name=Lower('cate_name')).order_by('cate_name')

    # 카테고리를 눌렀을 때 해당 카테고리에 포함되어 있는 post만 출력시키는 기능을 위함
    for cate in categorys:
        # cate_name이 소문자로 되어있기 때문에 lower()함수를 사용해 소문자로 변경해줌
        if cate.cate_name.lower() == cate_name:
            category_id = cate.id
            
    posts = Post.objects.filter(cate_id=category_id).annotate(comments_count=Count('comments'), category_title=F('cate__cate_name')).order_by('-id')
    
    all_post = 0
    for category in categorys:
        all_post += category.post_count

    context = {'categorys' : categorys, 'posts' : posts, 'cate_name' : cate_name, 'all_post' : all_post}
    return render(request, 'mypage/category.html', context)

# login.html / 로그인 페이지
def login_view(request):
    
    if request.method == "POST":
        username = request.POST['u_id']
        password = request.POST['u_pw']

        # username과 password가 일치한지 확인
        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return redirect('/')
        else:
            print("login failed")

    return render(request, 'mypage/login.html')

# 로그아웃은 따로 페이지가 필요없음
def logout_view(request):

    logout(request)

    return redirect('/')

# detail.html / 포스트 상세 페이지
def post_detail(request, post_id):
    # 특정 post를 클릭했을 때 해당 Post의 상세 페이지로 이동시키기 위함
    post = Post.objects.annotate(category_title=F('cate__cate_name')).get(id=post_id)
    categorys = Category.objects.all()

    # 만약 POST method를 요청했을 때 수행되는 구문
    # 상세페이지를 들어갔을 때 DB에서 정보를 가져오기 위해 GET을 하게 되는데 해당 조건문을 달지않으면 상세페이지를 들어갈 때마다 POST를 수행하기 때문에 빈 값을 보내게 되어 오류 발생
    if request.method == "POST":
        # detail.html에 있는 input의 name값을 기반으로 value를 가져옴
        comment_content = request.POST["comment"]
        comment_id = request.POST["comment_id"]
        comment_pw = request.POST["comment_pw"]

        Comments.objects.create(
            p_id = post_id,
            c_contents = comment_content,
            c_user_id = comment_id,
            c_user_pw = comment_pw,
            c_created = timezone.now(),
            c_updated = timezone.now()
        )
        
    context = {'post' : post, 'categorys' : categorys}
    return render(request, 'mypage/detail.html', context)

# write.html / 포스트 작성 페이지
def post_write(request):
    categorys = Category.objects.all()
    context = {'categorys' : categorys}

    # 위와 동일
    if request.method == "POST":
        cate = request.POST["categorys"]
        title = request.POST["title"]
        description = request.POST["description"]    
        content = request.POST["content"]

        # 썸네일 이미지 파일을 가져오기 위함
        # 예외구문을 사용하지 않고 썸네일을 넣지 않는 경우 오류 발생
        # 따라서 썸네일을 넣지 않는 경우에는 None을 입력
        try:
            thumbnail = request.FILES["thumbnail"]
        except:
            thumbnail = None

        post = Post.objects.create(
            cate_id = int(cate),
            p_title = title,
            p_desc = description,
            p_contents = content,
            p_created = timezone.now(),
            p_updated = timezone.now(),
            thumbnail = thumbnail
        )
        # redirect를 통해 게시글 작성을 완료하면 해당 post 상세페이지로 이동
        return redirect(f"/posts/{post.id}")
    
    return render(request, 'mypage/write.html', context)

# modify.html / 포스트 수정 페이지
def modify(request, post_id):
    post = Post.objects.get(id=post_id)
    categorys = Category.objects.all()
    
    # 위와 동일
    if request.method == "POST":
        post.cate_id = request.POST["categorys"]
        post.p_title = request.POST["title"]
        post.p_desc = request.POST["description"]    
        post.p_contents = request.POST["content"]
        post.p_updated = timezone.now()

        # 썸네일 이미지 파일을 가져오기 위함
        # 이때 썸네일을 수정하지 않는 경우 기존의 썸네일을 가져가도록 하기 위함
        try:
            post.thumbnail = request.FILES["thumbnail"]
        except:
            post.thumbnail = post.thumbnail
        # 포스트 내용 업데이트
        post.save()
        # redirect를 통해 게시글 작성을 완료하면 해당 post 상세페이지로 이동
        return redirect(f"/posts/{post.id}")

    context = {'post' : post, 'categorys' : categorys}
    return render(request, 'mypage/modify.html', context)

# 포스트 삭제
def delete(request, post_id):
    # 해당 포스트에 대한 정보만 가져오기 위함
    post = Post.objects.get(id=post_id)
    # 해당 포스트 삭제
    post.delete()
    # 포스트를 삭제한 뒤 메인페이지로 이동
    return redirect('/')

# 댓글 삭제
def delete_comment(request, comments_id):
    # 해당하는 댓글에 대한 정보만 가져오기 위함
    comment = Comments.objects.get(id=comments_id)
    
    if request.method == "POST":
        c_id = request.POST["c_id"]
        c_pw = request.POST["c_pw"]

        # 입력한 아이디와 비밀번호가 등록되어있는 아이디와 비밀번호가 동일한지 확인
        # 만약 동일하다면 해당 댓글 삭제
        if c_id == comment.c_user_id and c_pw == comment.c_user_pw:
            comment.delete()

        # 댓글을 삭제한 뒤, 댓글이 있었던 포스트로 이동
        return redirect(f"/posts/{comment.p_id}")
        
    return render(request, 'mypage/comment_delete.html')

def category_option(request):
    categorys = Category.objects.all().order_by('cate_name')

    if request.method == "POST":
        category_name = request.POST['cate_name']

        Category.objects.create(
            cate_name = category_name
        )

    context = {'categorys' : categorys}
    return render(request, "mypage/category_option.html", context)

def category_delete(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    return redirect('/option')

def category_modify(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'category' : category}

    if request.method == "POST":
        category.cate_name = request.POST['cate_name']

        category.save()
        return redirect('/option')
    
    return render(request, 'mypage/category_modify.html', context)

def about(request):

    return render(request, 'mypage/about.html')

config/templates/mypage/about.html
{% extends "./base.html" %}
{% load static %}
{% block login %}

  <!-- static 폴더내에 존재하는 about.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/about.css' %}"/>

  <div class="description">
    <i class="fa-solid fa-hammer"></i>
    <p>페이지 제작중</p>
    <i class="fa-solid fa-wrench"></i>
  </div>
{% endblock %}

config/templates/mypage/base.html
<!-- 모든 templates의 부모가 되는 html 파일 -->
<!-- header / sidebar / footer가 모든 templates에 존재하기 때문에 코드의 중복을 제거하기 위해 block, extends 이용 -->
<!-- block에 해당하는 부분에 자식의 정보들이 들어감 -->

{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- 아이콘 사용 -->
    <script src="https://kit.fontawesome.com/9ef1e52ac8.js" crossorigin="anonymous"></script>

    <!-- static 폴더내에 존재하는 default.css 파일 사용 -->
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>

    <!-- nav-bar 토글 사용을 위한 JS코드 사용 -->
    <script src="{% static 'js/main.js' %}" defer="defer"></script>

    <title>hyodev</title>

    <!-- favicon 사용-->
    <link rel="icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">

  </head>

  <body>
    <div class="container">
      <!-- 헤더 -->
      <div class="header-background">
        <div class="header">
          <div class="head-logo">
            <a href="/">
              <i class="fa-solid fa-code"></i>
              hyodev</a>
          </div>
          <ul class="head-menu">
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/category">Category</a>
            </li>
            <li>
              <a target="_blank" href="mailto:alexization@naver.com?subject=contact e-mail">Contact</a>
            </li>
          </ul>
          <ul class="head-link">
            <li>
              {% if user.is_active %}
                <a href="/logout">
                  <i class="fa-solid fa-arrow-right-from-bracket"></i>
                  Logout</a>
              {% else %}
                <a href="/login">
                  <i class="fa-solid fa-arrow-right-to-bracket"></i>
                  Login</a>
              {% endif %}
            </li>
          </ul>
          <a href="#" class="navbar_toggleBtn">
            <i class="fa-solid fa-bars"></i>
          </a>
        </div>
      </div>

      {% block index %}{% endblock %}
      {% block category %}{% endblock %}
      {% block detail %}{% endblock %}
      {% block write %}{% endblock %}
      {% block about %}{% endblock %}
      {% block login %}{% endblock %}
      {% block modify %}{% endblock %}
      {% block category_option %}{% endblock %}
      {% block category_modify %}{% endblock %}

      <!-- 하단바 공간 -->
      <div class="footer">
        <div class="head-title">
          <i class="fa-solid fa-code"></i>
          <a href="/">hyodev</a>
        </div>
        <p class="copyright">© 2023 Hyo Seok, Baek. All rights reserved</p>
      </div>

      <!-- 클릭시 맨 위로 이동 -->
      <button class="go-first" onclick="window.scrollTo(0,0);">
        <i class="fa-solid fa-chevron-up"></i>
      </button>
    </div>
  </body>

</html>

config/templates/mypage/category.html
{% extends "./base.html" %}{% load static %}
{% block index %}
  <!-- static 폴더내에 존재하는 category.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/category.css' %}"/>

  <div class="category-list">
    {% for category in categorys %}
      <!-- 선택한 카테고리는 색을 변경 -->
      {% if cate_name == category.lower_name %}
        <div onclick="location.href='/category/{{ category.cate_name | lower}}/';" class="category-box" style="background-color:#a75e2d">
          <div>{{ category.cate_name }}</div>
          <div class="category-count">
            (
            {{ category.post_count }}
            )</div>
        </div>

      {% else %}
        <div onclick="location.href='/category/{{ category.cate_name | lower}}/';" class="category-box">
          <div>{{ category.cate_name }}</div>
          <div class="category-count">
            (
            {{ category.post_count }}
            )</div>
        </div>
      {% endif %}
    {% endfor %}
  </div>

  <!-- 게시글 목록 공간 -->
  <div class="middle">
    <!-- 게시글 박스 -->
    <div class="content">
      {% for post in posts %}
        <div onclick="location.href='/posts/{{ post.id }}/';" class="post-box">
          <div class="content-text">
            <p class="content-title">{{ post.p_title }}</p>
            <div class="sub-detail">
              <p>
                <i class="fa-solid fa-bookmark" style="color:#CC0000"></i>
                {{ post.category_title }}</p>
              <p>
                <i class="fa-regular fa-calendar" style="color:#660000"></i>
                {{ post.p_created | date:'Y-m-d'}}</p>
              <p>
                <i class="fa-regular fa-comment-dots"></i>
                댓글
                {{post.comments_count }}건</p>
            </div>
            <p class="content-description">{{ post.p_desc | truncatechars:90}}</p>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  {% endblock %}

config/templates/mypage/category_modify.html
{% extends "./base.html" %}
{% load static %}
{% block category_modify %}

  <!-- static 폴더내에 존재하는 category_option.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/category_option.css' %}"/>

  <div class="description">카테고리명 변경</div>

  <!-- 새로운 카테고리 추가 -->
  <form method="POST" class="add-category">
    {% csrf_token %}
    <input type="text" name="cate_name" placeholder="카테고리명" value='{{ category.cate_name }}' required="required"/>
    <button type="submit" onclick="return confirm('카테고리명을 변경하시겠습니까?');">
      변경
    </button>
  </form>

{% endblock %}

config/templates/mypage/category_option.html
{% extends "./base.html" %}
{% load static %}
{% block category_option %}

  <!-- static 폴더내에 존재하는 category_option.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/category_option.css' %}"/>

  <div class="description">카테고리 관리</div>

  <!-- 새로운 카테고리 추가 -->
  <form method="POST" class="add-category">
    {% csrf_token %}
    <input type="text" name="cate_name" placeholder="카테고리명" required="required"/>
    <button type="submit" onclick="return confirm('새로운 카테고리를 추가하시겠습니까?');">
      추가
    </button>
  </form>

  <!-- 카테고리 수정 및 삭제 -->
  {% for category in categorys %}
    <div class="category-box">
      <div>{{ category.cate_name }}</div>
      <div>
        <a href="/option/modify/{{category.id}}" class="modify">
          <i class="fa-solid fa-pen"></i>
        </a>
        <a href="/option/delete/{{category.id}}" class="delete" onclick="return confirm('해당 카테고리를 삭제하시겠습니까?');">
          <i class="fa-solid fa-trash-can"></i>
        </a>
      </div>
    </div>
  {% endfor %}
{% endblock %}

config/templates/mypage/comment_delete.html
{% extends "./base.html" %}
{% load static %}
{% block login %}

  <!-- static 폴더내에 존재하는 comment.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/comment.css' %}"/>

  <div class="description">댓글 삭제하기</div>
  <form method="POST" class="input-box">
    {% csrf_token %}
    <div class="input-info">
      <input type="text" name="c_id" placeholder="아이디" required="required">
      <input type="password" name="c_pw" placeholder="비밀번호" / required="required">
    </div>
    <button type="submit" class="button-box">확인</button>
  </form>

{% endblock %}

config/templates/mypage/detail.html
{% extends "./base.html" %}
{% load static %}
{% block detail %}

  <!-- static 폴더내에 존재하는 detail.css 파일 사용 -->
  <link rel="stylesheet" type="text/css" href="{% static 'markdownx/admin/css/markdownx.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/detail.css' %}"/>
  <script src="{% static 'markdownx/js/markdownx.js' %}" defer="defer"></script>

  <!-- 게시글 상세 내용 -->
  <div class="content">
    <!-- 썸네일 및 날짜 / 내용 -->
    <div class="content-text">
      <!-- 썸네일 -->
      <div class="thumbnail">
        {% if post.thumbnail %}
          <img src="{{post.thumbnail.url}}"/>
        {% endif %}
      </div>
      <!-- 게시글 제목 -->
      <div class="title">{{post.p_title}}</div>
      <!-- 게시글 설명 -->
      <div class="description">{{post.p_desc}}</div>
      <!-- 게시글 게시 및 수정 날짜 -->
      <div class="date">
        {{post.p_created | date:'Y.m.d H:m'}}
        ・
        {{post.category_title}}
      </div>
      <!-- 게시글 내용 -->
      <div class="post-detail">
        <div class="markdownx">
          <div class="markdownx-preview">
            {{ post.get_content_markdown | safe }}
          </div>
        </div>
      </div>
    </div>

    <!-- 수정 / 삭제 버튼 -->
    {% if user.is_active %}
      <div class="button-box">
        <a href="/modify/{{post.id}}" class="modify">
          <i class="fa-solid fa-file-pen"></i>
          수정하기</a>

        <!-- 삭제는 따로 html 파일을 제작하지 않고 팝업창으로 확인 -->
        <a href="/delete/{{post.id}}" class="delete" onclick="return confirm('정말 삭제하시겠습니까?');">
          <i class="fa-solid fa-trash-can"></i>
          삭제하기</a>
      </div>
    {% endif %}

    <!-- 댓글 작성 -->
    <div class="comment-box">
      <div class="comment-text">댓글</div>

      <!-- 댓글 입력 박스 -->
      <form method="POST" class="comment-input">
        {% csrf_token %}

        <!-- 아이디 / 비밀번호 입력 -->
        <div class="input-info">
          <input type="text" name="comment_id" placeholder="아이디" style="outline: none" required="required"/>
          <input type="password" name="comment_pw" placeholder="비밀번호" style="outline: none" required="required"/>
        </div>

        <!-- 댓글 내용 / 버튼 -->
        <div class="input-comment">
          <textarea name="comment" placeholder="댓글을 입력해주세요." style="outline: none" required="required"></textarea>
          <button type="submit">댓글<br/>작성</button>
        </div>
      </form>

      <!-- 댓글 확인 박스 -->
      <ul class="comments">
        {% for comment in post.comments_set.all %}
          <li class="comment">
            <div style="width: 10%; font-weight: 200">
              {{comment.c_user_id}}
            </div>
            <div style="width: 70%">{{ comment.c_contents }}</div>
            <div style="width: 20%; font-weight: 200; text-align: end">
              {{comment.c_updated | date:'m.d H:m' }}
              <a href="/comment/{{comment.id}}">
                <i class="fa-regular fa-rectangle-xmark"></i>
              </a>
            </div>
          </li>

          <!-- 댓글이 없는 경우 -->
          {% empty %}
          <li class="comment-empty">아직 댓글이 없습니다</li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

config/templates/mypage/index.html
{% extends "./base.html" %}{% load static %}
{% block index %}
  <!-- static 폴더내에 존재하는 index.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/index.css' %}"/>

  <!-- 상단 프로필 -->
  <div class="profile">
    <div class="profile-text">
      <span>기록을 안 하면 하나도 기억이 안 나더라...</span></div>
    <div class="profile-info">
      <div class="profile-img"><img src="{% static 'image/profile.jpeg' %}"/>
      </div>
      <div class="profile-tag">
        <div class="profile-name">Hyo Seok, Baek</div>
        <div class="profile-desc">하나하나 채워나가는 개발 일기장</div>
        <ul class="profile-link">
          <li>
            <a href="https://www.instagram.com" target="_blank">
              <i class="fa-brands fa-instagram"></i>
            </a>
          </li>
          <li>
            <a href="https://www.github.com/alexization" target="_blank">
              <i class="fa-brands fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- 글쓰기 버튼 공간 -->
  <div class="write-box">
    {% if user.is_active %}
      <button onclick="location.href='/write/';" class="write-button">
        글쓰기
      </button>
    {% endif %}
  </div>

  <!-- 게시글 목록 공간 -->
  <div class="middle">
    <!-- 게시글 박스 -->
    <div class="content">
      {% for post in posts %}
        <div onclick="location.href='/posts/{{ post.id }}/';" class="post-box">
          <div class="content-text">
            <p class="content-title">{{ post.p_title }}</p>
            <div class="sub-detail">
              <p>
                <i class="fa-solid fa-bookmark" style="color:#CC0000"></i>
                {{ post.category_title }}</p>
              <p>
                <i class="fa-regular fa-calendar" style="color:#660000"></i>
                {{ post.p_created | date:'Y-m-d'}}</p>
              <p>
                <i class="fa-regular fa-comment-dots"></i>
                댓글
                {{post.comments_count }}건</p>
            </div>
            <p class="content-description">{{ post.p_desc | truncatechars:90}}</p>
          </div>
        </div>
        {% endfor%}
      </div>
    </div>
  {% endblock %}

config/templates/mypage/login.html
{% extends "./base.html" %}
{% load static %}
{% block login %}

  <!-- static 폴더내에 존재하는 comment.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/comment.css' %}"/>

  <div class="description">관리자 로그인</div>
  <form method="POST" class="input-box">
    {% csrf_token %}
    <div class="input-info">
      <input type="text" name="u_id" placeholder="아이디" required="required">
      <input type="password" name="u_pw" placeholder="비밀번호" required="required"/>
    </div>
    <button type="submit" class="button-box">확인</button>
  </form>

{% endblock %}

config/templates/mypage/modify.html
{% extends "./base.html" %}
{% load static %}
{% block modify %}

  <!-- static 폴더내에 존재하는 modify.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/modify.css' %}"/>

  <!-- 게시글 수정 박스 -->
  <form method="POST" enctype="multipart/form-data" class="post-box">
    {% csrf_token %}

    <!-- 수정 버튼 공간 -->
    <div class="button-box">
      <div></div>
      <div>게시글 수정하기</div>
      <button type="submit" class="write-button" onclick="return confirm('변경된 사항을 반영하시겠습니까?');">수정하기</button>
    </div>

    <!-- 제목 / 설명 / 내용 -->
    <input type="text" name="title" placeholder="게시글 제목" value="{{ post.p_title }}" required="required">
    <input type="text" name="description" placeholder="게시글 설명 • 게시글에 대한 간단한 요약" value="{{ post.p_desc }}" required="required"/>
    <textarea name="content" cols="50" rows="40" placeholder="내용을 입력해주세요.">{{post.p_contents}}</textarea>

    <!-- 카테고리 선택 -->
    <label for="category" style="height: 50px">카테고리
      <select name="categorys" id="category">
        {% for cate in categorys %}
          <option value="{{ cate.id }}">{{ cate.cate_name }}</option>
        {% endfor %}
      </select>
    </label>

    <!-- 썸네일 -->
    <label>썸네일
      <input name="thumbnail" type="file"/></label>
  </form>
{% endblock %}

config/templates/mypage/write.html
{% extends "./base.html" %}
{% load static %}
{% block write %}

  <!-- static 폴더내에 존재하는 write.css 파일 사용 -->
  <link rel="stylesheet" href="{% static 'css/write.css' %}"/>

  <!-- 게시글 작성 박스 -->
  <form method="POST" enctype="multipart/form-data" class="post-box">
    {% csrf_token %}

    <!-- 작성 버튼 공간 -->
    <div class="button-box">
      <div></div>
      <div>새로운 게시글 작성하기</div>
      <button type="submit" class="write-button" onclick="return confirm('게시글을 작성하시겠습니까?');">글쓰기</button>
    </div>

    <!-- 제목 / 설명 / 내용 -->
    <input type="text" name="title" placeholder="게시글 제목" required="required"/>
    <input type="text" name="description" placeholder="게시글 설명 • 게시글에 대한 간단한 요약" required="required"/>
    <textarea name="content" cols="50" rows="40" placeholder="내용을 입력해주세요."></textarea>

    <!-- 카테고리 선택 -->
    <label for="category" style="height: 50px">카테고리
      <select name="categorys" id="category">
        {% for cate in categorys %}
          <option value="{{ cate.id }}">{{ cate.cate_name }}</option>
        {% endfor %}
      </select>
    </label>

    <!-- 썸네일 -->
    <label>썸네일
      <input name="thumbnail" type="file"/></label>
  </form>
{% endblock %}